### ISSUE TITLE
Node.js client not working behind Proxy

### ISSUE THREAD

**Issue by hkarekar** [LeanKit/leankit-node-client#1]
Hi,

I have tried this behind a proxy server and it somehow is not able to make that call.
Once I disconnect my corporate vpn and the connection is made directly to the internet, the same code works fine.

Please check this.

Txm
Hrishikesh Karekar

**Comment by reverentgeek** [comment]
My apologies for not following up on this issue. The client does work behind a proxy and now includes instructions in the readme on how to configure.
