### ISSUE TITLE
Add ability to create a board via API

### ISSUE THREAD

**Issue by bobeagan** [LeanKit/leankit-node-client#10]
I'd love to be able to create boards via the API.  Any idea if this functionality is planned?

**Comment by reverentgeek** [comment]
Hi Bob,

I had forgotten about it, but we do have one undocumented API endpoint for creating a board based on a board template. Basically, there are two parameters: `templateName` and `title`. 

However, there are no APIs for board access, settings, and a number of other important features for managing boards after the initial creation process.

**Comment by bobeagan** [comment]
That's a bummer. Any idea if that's ever going to be a thing?

**Comment by reverentgeek** [comment]
We don't have any specific plans in this area. If it does become a thing, it certainly won't be this year. New API work is underway, but board management is much lower in priority compared to card and user management.

**Comment by bobeagan** [comment]
And no other undocumented ways to accomplish it?

**Comment by reverentgeek** [comment]
I sent you a direct message using the email address on your GitHub profile.
