### ISSUE TITLE
Empty string for BlockStateChangeDate

### ISSUE THREAD

**Issue by bobeagan** [LeanKit/leankit-node-client#11]
Not sure if this should contain what I think it should (the last date that the block state was changed on a card) but currently when inspecting this value, after doing a getBoard and scanning through Lanes and then Cards, it seems to always show as an empty string whether the card is currently blocked or not.  Does this value mean something different?

**Comment by reverentgeek** [comment]
I've confirmed, and I'm filing this as an issue with our product team. The only work-around I can think of right now is to get a card's history to determine when it was blocked or unblocked.
