### ISSUE TITLE
Error when reading Board API

### ISSUE THREAD

**Issue by ryanddunn** [LeanKit/leankit-node-client#12]
I followed the simple "gettings started" tutorial (http://developer.leankit.com/automate-leankit-with-node-js/) on Lean Kit's website and I'm getting the following error. 

Error getting boards: [TypeError: Object boards has no method 'startsWith']

Despite confirming that my Company Name, Username, and Password are all correct. Can anyone shed some light on this for me? 

--------------------
```

// Reference the LeanKit client
var LeanKitClient = require( "leankit-client" );

// Update this variable to the name of your LeanKit 
// account, which can be found in the URL you use 
// to access your LeanKit boards. For example, 
// https://mycompany.leankit.com
var accountName = "mycompany";

// Update this variable to your email address
var email = "me@mycompany.com";

// Update this variable to your LeanKit password
var password = "p@ssw0rd";

// Create an instance of the client with your credentials
var client = new LeanKitClient( accountName, email, password );

client.getBoards( function( err, boards ) {  
  if ( err ) console.error( "Error getting boards:", err );
  console.log( boards );
} );
```

**Comment by reverentgeek** [comment]
Hi Ryan,

What version of Node.js are you running? You can go to the command prompt  or terminal and type `node -v`.

**Comment by ryanddunn** [comment]
I solved the issue, I had an issue with the node libraries.

Thanks for getting back to me.

Ryan Dunn
http://RyanDunn.co/contact

**Comment by reverentgeek** [comment]
Ok, glad to hear you got it resolved. If you have any further questions, feel free to open another issue or send them to support@leankit.com!
