### ISSUE TITLE
LeanKit API with node.js

### ISSUE THREAD

**Issue by lihp123** [LeanKit/leankit-node-client#13]
Hello,

i am already using the leankit-node-client, and everything is working fine.
I was just wondering how to use the GET and POST operations from {accountname}.leankit.com/io/docs
Tried it using the require module and the express module, but it didn't relly work. Now I was wondering if i could integrate it in the leankit-node-client?
Or does anyone has some example script?
Esspecially regarding the create and delete template commands.
Thankful for any help

**Comment by lihp123** [comment]
Okay, got it. If someone is interested:
you can find different kinds of api requests at: {accountname}.leankit.com/io/docs
Example would be: GET https://{accountname}.leankit.com/io/user
If you want to use it in your node.js scripts, do the following:
1. open the Leankit-client node.js module and edit the client.js:
Copy this under clientGet:
	var clientGetNeu = function clientGetNeu(path, callback) {
		var p = when.promise(function (resolve, reject) {
			client.get(path, function (err, res, body) {
				if (err) {
					if (err instanceof Error) {
						reject(err);
					} else {
						var error = new Error("httpGetError");
						error.details = err;
						reject(error);
					}
				} else {
					parseReplyData(err, res, body, function (parseErr, parsed) {
						if (!parseErr) {
							resolve(parsed);
						} else {
							reject(parseErr);
						}
					});
				}
			});
		});		
		if (typeof callback === "function") {
			p.then(function (res) {
				return callback(null, res);
			}).catch(function (err) {
				return callback(err);
			});
		} else {
			return p;
		}
	};


the difference to clientGet is that this function doesnt check the path.
Now create one new function in client.js:

	var getAPI = function getAPI(url, callback) {
		return clientGetNeu(url, callback);
	};


now you can call this function in your node.js script using
client.getAPI("/io/user", function(err, boards){
	if(err) console.error(err);
	console.log(boards);
});

Which will get you the active users.

**Comment by reverentgeek** [comment]
Apologies for the late reply. I thought you would like to know the latest version the LeanKit Node.js client includes support for the newer `/io/` API endpoints. Please let us know if you have any questions.
