### ISSUE TITLE
classic access control problem

### ISSUE THREAD

**Issue by jamesalbert** [LeanKit/leankit-node-client#20]
```
Fetch API cannot load https://<site>.leankit.com/io/card. Response to preflight
request doesn't pass access control check: No 'Access-Control-Allow-Origin'
header is present on the requested resource. Origin 'http://localhost:3000' is
therefore not allowed access. If an opaque response serves your needs, set
the request's mode to 'no-cors' to fetch the resource with CORS disabled
```

Everything works as a standalone script, but when I plug it into my site, I get this error. I feel dumb for not being able to solve this. I thought authenticating would make leankit return an access control header, but it didn't 😞

**Comment by reverentgeek** [comment]
Hi James,

The API client is not intended to be used as a client-side library. For security reasons, our APIs do not support any type of cross-origin requests (CORS). 

One possible work-around is your client-side code makes an AJAX request to your own back-end Node.js server, the server makes the request(s) to LeanKit using the API client, and then returns the data your web client needs.

Best regards,
David

**Comment by jamesalbert** [comment]
@reverentgeek Thanks for the quick response, yeah that's what I ended up doing. Cool, I'll go ahead and close this then 👍
