### ISSUE TITLE
getCardByExternalId() does not find cards in taskboards

### ISSUE THREAD

**Issue by bobeagan** [LeanKit/leankit-node-client#9]
I'd expect to be able to find a card anywhere, including on a taskboard using this function.

**Comment by reverentgeek** [comment]
My apologies for not following up on this issue. Unfortunately, this is not something supported by our API at this time. I think this would be a great suggestion to add to our [feature requests](https://support.leankit.com/hc/communities/public/topics/200138903-Community-Feature-Requests).
